--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TynaevCode/GmInventories
build-by-default: true
branches:
- Be
projects:
  GmInventories:
    path: ""
    libs:
      - src: poggit/libasynql/libasynql
        version: ^4.1.6
...
